<?php

/*
 *     /$$$$$$$           /$$               /$$
 *   | $$__  $$         | $$              | $$
 *   | $$  \ $$/$$$$$$ /$$$$$$   /$$$$$$ /$$$$$$   /$$$$$$  /$$$$$$  /$$$$$$$
 *   | $$$$$$$/$$__  $|_  $$_/  |____  $|_  $$_/  /$$__  $$/$$__  $$/$$_____/
 *   | $$____| $$  \ $$ | $$     /$$$$$$$ | $$   | $$  \ $| $$$$$$$|  $$$$$$
 *   | $$    | $$  | $$ | $$ /$$/$$__  $$ | $$ /$| $$  | $| $$_____/\____  $$
 *   | $$    |  $$$$$$/ |  $$$$|  $$$$$$$ |  $$$$|  $$$$$$|  $$$$$$$/$$$$$$$/
 *   |__/     \______/   \___/  \_______/  \___/  \______/ \_______|_______/
 *
 *  GNU General Public License v2.0
 *  Copyright (C) 1989, 1991 Free Software Foundation, Inc.
 *  51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 *  Everyone is permitted to copy and distribute verbatim copies
 *  of this license document, but changing it is not allow
 */

namespace Refaltor\Natof\CustomItem\Items;

use pocketmine\block\Block;
use pocketmine\block\BlockIds;
use pocketmine\item\Hoe;
use pocketmine\math\Vector3;
use pocketmine\Player;

class HoeItem extends Hoe
{
    /** @var string */
    private string $texturePath;

    /** @var int */
    private int $creativeCategory = 3;

    /** @var float */
    private float $damageTools;

    /** @var float */
    private float $durability;

    public function __construct(int $id, int $meta, string $name, int $tier, float $damageTools, float $durability)
    {
        $this->durability = $durability;
        $this->damageTools = $damageTools;
        $this->texturePath = 'barrier';
        parent::__construct($id, $meta, $name, $tier);
    }

    public function getMaxDurability(): int
    {
        return $this->durability;
    }

    /**
     * @param string $path
     * @return $this
     */
    public function setTexture(string $path): self
    {
        $this->texturePath = $path;
        return $this;
    }

    /**
     * @return string
     */
    public function getTexture(): string
    {
        return $this->texturePath;
    }

    public function getAttackPoints(): int
    {
        return $this->damageTools; // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getCreativeCategory(): string
    {
        return $this->creativeCategory;
    }


    /**
     * @param Player $player
     * @param Block $blockReplace
     * @param Block $blockClicked
     * @param int $face
     * @param Vector3 $clickVector
     */

    public function onActivate(Player $player, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector): bool
    {
        if (in_array($blockClicked->getId(), [BlockIds::DIRT, BlockIds::GRASS]) && $face == 1) {
            $player->getLevel()->setBlock($blockClicked, Block::get(Block::FARMLAND));
        }
        return parent::onActivate($player, $blockReplace, $blockClicked, $face, $clickVector);
    }
}