<?php

/*
 *     /$$$$$$$           /$$               /$$
 *   | $$__  $$         | $$              | $$
 *   | $$  \ $$/$$$$$$ /$$$$$$   /$$$$$$ /$$$$$$   /$$$$$$  /$$$$$$  /$$$$$$$
 *   | $$$$$$$/$$__  $|_  $$_/  |____  $|_  $$_/  /$$__  $$/$$__  $$/$$_____/
 *   | $$____| $$  \ $$ | $$     /$$$$$$$ | $$   | $$  \ $| $$$$$$$|  $$$$$$
 *   | $$    | $$  | $$ | $$ /$$/$$__  $$ | $$ /$| $$  | $| $$_____/\____  $$
 *   | $$    |  $$$$$$/ |  $$$$|  $$$$$$$ |  $$$$|  $$$$$$|  $$$$$$$/$$$$$$$/
 *   |__/     \______/   \___/  \_______/  \___/  \______/ \_______|_______/
 *
 *  GNU General Public License v2.0
 *  Copyright (C) 1989, 1991 Free Software Foundation, Inc.
 *  51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 *  Everyone is permitted to copy and distribute verbatim copies
 *  of this license document, but changing it is not allow
 */

namespace Refaltor\Natof\CustomItem\Items;

use pocketmine\block\Block;
use pocketmine\entity\Entity;
use pocketmine\item\Pickaxe;
use pocketmine\math\Vector3;

class PickaxeItem extends Pickaxe
{
    /** @var string */
    private string $texturePath;

    /** @var int */
    private int $creativeCategory = 3;

    /** @var float */
    private float $damageTools;

    /** @var float */
    private float $durability;
    /** @var float */
    private float $efficiency;

    public function __construct(int $id, int $meta, string $name, int $tier, float $damageTools, float $durability, float $efficiency)
    {
        $this->efficiency = $efficiency;
        $this->durability = $durability;
        $this->damageTools = $damageTools;
        $this->texturePath = 'barrier';
        parent::__construct($id, $meta, $name, $tier);
    }

    public function getMaxDurability(): int
    {
        return $this->durability;
    }

    public function getMiningEfficiency(Block $block): float
    {
        return $this->efficiency;
    }

    /**
     * @param string $path
     * @return $this
     */
    public function setTexture(string $path): self
    {
        $this->texturePath = $path;
        return $this;
    }

    /**
     * @return string
     */
    public function getTexture(): string
    {
        return $this->texturePath;
    }

    public function getAttackPoints(): int
    {
        return $this->damageTools; // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getCreativeCategory(): string
    {
        return $this->creativeCategory;
    }
}