<?php

/*
 *     /$$$$$$$           /$$               /$$
 *   | $$__  $$         | $$              | $$
 *   | $$  \ $$/$$$$$$ /$$$$$$   /$$$$$$ /$$$$$$   /$$$$$$  /$$$$$$  /$$$$$$$
 *   | $$$$$$$/$$__  $|_  $$_/  |____  $|_  $$_/  /$$__  $$/$$__  $$/$$_____/
 *   | $$____| $$  \ $$ | $$     /$$$$$$$ | $$   | $$  \ $| $$$$$$$|  $$$$$$
 *   | $$    | $$  | $$ | $$ /$$/$$__  $$ | $$ /$| $$  | $| $$_____/\____  $$
 *   | $$    |  $$$$$$/ |  $$$$|  $$$$$$$ |  $$$$|  $$$$$$|  $$$$$$$/$$$$$$$/
 *   |__/     \______/   \___/  \_______/  \___/  \______/ \_______|_______/
 *
 *  GNU General Public License v2.0
 *  Copyright (C) 1989, 1991 Free Software Foundation, Inc.
 *  51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 *  Everyone is permitted to copy and distribute verbatim copies
 *  of this license document, but changing it is not allow
 */

namespace Refaltor\Natof\CustomItem\Items;

use pocketmine\item\Armor;
use pocketmine\item\ArmorTypeInfo;
use pocketmine\item\Item;
use pocketmine\item\ItemIdentifier;
use pocketmine\item\Sword;
use pocketmine\item\TieredTool;
use pocketmine\item\ToolTier;

class SwordItem extends Sword
{
    /** @var string  */
    private string $texturePath;

    /** @var int */
    private int $creativeCategory = 3;

    /** @var float  */
    private float $damageSword = 0;

    /** @var float  */
    private float $durability;

    public function __construct(ItemIdentifier $identifier, string $name, ToolTier $tier, float $damageSword, float $durability)
    {
        $this->durability = $durability;
        $this->damageSword = $damageSword;
        $this->texturePath = 'barrier';
        parent::__construct($identifier, $name, $tier);
    }

    public function getMaxDurability(): int
    {
        return $this->durability;
    }


    /**
     * @param string $path
     * @return $this
     */
    public function setTexture(string $path): self {
        $this->texturePath = $path;
        return $this;
    }

    /**
     * @return string
     */
    public function getTexture(): string {
        return $this->texturePath;
    }

    public function getAttackPoints(): int
    {
        return $this->damageSword; // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getCreativeCategory(): string {
        return $this->creativeCategory;
    }
}